# Permutation

In [3]:
import numpy as np

In [45]:
class Permutation:
    def __init__(self, p: list):
        if max(p) == len(p):
            self.permutation = np.array(p)
        else:
            self.permutation = np.arange(1, len(p)+1)
        
        self.size = self.permutation.size
        self.idx = 0
    
    def __str__(self):
        return f'{np.arange(1, len(self.permutation)+1)}, {self.permutation}'
    
    def __repr__(self):
        return f'{np.arange(1, len(self.permutation)+1)}, {self.permutation}'
    
    def __iter__(self):
        self.idx = 0
        return self
    
    def __next__(self):
        try:
            item = self.permutation[self.idx]
        except IndexError:
            raise StopIteration()
        self.idx += 1
        return item

    def get(self, index):
        return self.permutation[index]
        
    def shuffle(self):
        np.random.shuffle(self.permutation)
    
    def get_inverse(self):
        pass


class Composition:
    def __init__(self, permutations: list):
        self.permutations = permutations
        self.SIZE = permutations[0].size
    
    def make_composition(self, a, b):
        compos = np.zeros(self.SIZE, dtype=int)
        for n, i in enumerate(b):
            compos[n] = a.get(i-1)

        return compos
    
    def print_composition(self):
        pass



In [46]:
p1 = Permutation([3, 2, 1, 4])
p2 = Permutation([4, 2, 3, 1])

comp = Composition([p1, p2])

comp.make_composition(p1, p2)

array([4, 2, 1, 3])

In [26]:
p1

[1 2 3 4], [3 2 1 4]

In [39]:
p1.get(0)

3

In [29]:
for i in p2:
    print(i)

4
2
3
1


In [28]:
p1.get(0)

3

In [43]:
compos = np.zeros(p1.size, dtype=int)
for n, i in enumerate(p2):
    compos[n] = p1.get(i-1)

compos

array([4, 2, 1, 3])