# Permutation

In [2]:
import numpy as np

In [46]:
class Permutation:
    def __init__(self, p: list):
        if max(p) == len(p):
            self.permutation = np.array(p)
        else:
            self.permutation = np.arange(1, len(p)+1)
    
    def shuffle(self):
        np.random.shuffle(self.permutation)
    
    def show(self):
        print(np.arange(1, len(self.permutation)+1), self.permutation, sep='\n')
    
    def get_inverse(self):
        pass


class Composition:
    def __init__(self):
        pass



In [48]:
p1 = Permutation([3, 2, 1, 4])
p1.show()

[1 2 3 4]
[3 2 1 4]


In [42]:
p1.shuffle()
p1.show()

[1 2 3 4]
[2 1 4 3]
