# Permutation

In [1]:
import numpy as np

In [35]:
class Permutation:
    def __init__(self, p: list):
        if max(p) == len(p):
            self.permutation = np.array(p)
        else:
            self.permutation = np.arange(1, len(p)+1)
        
        self.size = self.permutation.size
        self.idx = 0
    
    def __str__(self):
        return f'{np.arange(1, len(self.permutation)+1)}, {self.permutation}'
    
    def __repr__(self):
        return f'{np.arange(1, len(self.permutation)+1)}, {self.permutation}'
    
    def __iter__(self):
#         self.idx = 0
        return self
    
    def __next__(self):
        if self.idx < len(self.permutation):
            self.idx += 1
            return self.permutation[self.idx-1]
        else:
            self.idx = 0
            return self.permutation[self.idx]

    def get(self, index):
        return self.permutation[index]
        
    def shuffle(self):
        np.random.shuffle(self.permutation)
    
    def get_inverse(self):
        pass


class Composition:
    def __init__(self, permutations: list):
        self.permutations = permutations
        self.SIZE = permutations[0].size
    
    def make_composition(self, a, b):
        compos = np.zeros(self.SIZE, dtype=int)
        for n, i in enumerate(b):
            compos[n] = a[i-1]

        return compos
    
    def print_composition(self):
        pass



In [36]:
p1 = Permutation([3, 2, 1, 4])
p2 = Permutation([4, 2, 3, 1])

comp = Composition([p1, p2])

comp.make_composition(np.array([3, 2, 1, 4]), np.array([4, 2, 3, 1]))

array([4, 2, 1, 3])

In [30]:
p1

[1 2 3 4], [3 2 1 4]

In [38]:
# iterator = iter(p1)
l = 0
for i in p1:
    if l < 4:
        l+=1
        print(i)
    else:
        break
    

3
2
1
4


In [79]:
p1

[1 2 3 4], [3 2 1 4]

In [70]:
p1.get(0)

3

In [24]:
a = np.array([3, 2, 1, 4])
b = np.array([4, 2, 3, 1])

np.where(a==2)[0][0]

1

In [37]:
compos = np.zeros(a.size, dtype=int)
for n, i in enumerate(b):
    compos[n] = a[i-1]

compos

array([4, 2, 1, 3])